repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # Use the latest version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
  - repo: https://github.com/psf/black
    rev: 24.10.0  # Use the latest version
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1  # Use the latest version
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-unused-arguments
